-- Product Table

CREATE TABLE [dbo].[Product] (
    [Id]          INT            IDENTITY (1, 1) NOT NULL,
    [Title]       NVARCHAR (MAX) NOT NULL,
    [Price]       FLOAT (53)     NOT NULL,
    [Description] NVARCHAR (MAX) NOT NULL,
    [Category]    NVARCHAR (MAX) NOT NULL,
    [Image]       NVARCHAR (MAX) NOT NULL,
    [RatingRate]  FLOAT (53)     NOT NULL,
    [RatingCount] FLOAT (53)     NOT NULL,
    CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED ([Id] ASC)
);
Go

--Insert Into Product

INSERT INTO [dbo].[Product] ([Id], [Title], [Price], [Description], [Category], [Image], [RatingRate], [RatingCount]) VALUES (1, N'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops', 109.95, N'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday', N'men''s clothing', N'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg', 3.9, 120)
INSERT INTO [dbo].[Product] ([Id], [Title], [Price], [Description], [Category], [Image], [RatingRate], [RatingCount]) VALUES (2, N'Mens Casual Premium Slim Fit T-Shirts', 22.3, N'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.', N'men''s clothing', N'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg', 4.1, 259)
INSERT INTO [dbo].[Product] ([Id], [Title], [Price], [Description], [Category], [Image], [RatingRate], [RatingCount]) VALUES (3, N'Mens Cotton Jacket', 55.99, N'great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.', N'men''s clothing', N'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg', 4.7, 500)
INSERT INTO [dbo].[Product] ([Id], [Title], [Price], [Description], [Category], [Image], [RatingRate], [RatingCount]) VALUES (4, N'Mens Casual Slim Fit', 15.99, N'The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.', N'men''s clothing', N'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg', 2.1, 430)
INSERT INTO [dbo].[Product] ([Id], [Title], [Price], [Description], [Category], [Image], [RatingRate], [RatingCount]) VALUES (5, N'John Hardy Women''s Legends Naga Gold & Silver Dragon Station Chain Bracelet', 695, N'From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean''s pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.', N'jewelery', N'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg', 4.6, 400)
INSERT INTO [dbo].[Product] ([Id], [Title], [Price], [Description], [Category], [Image], [RatingRate], [RatingCount]) VALUES (6, N'Solid Gold Petite Micropave', 168, N'Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.', N'jewelery', N'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg', 3.9, 70)
INSERT INTO [dbo].[Product] ([Id], [Title], [Price], [Description], [Category], [Image], [RatingRate], [RatingCount]) VALUES (7, N'White Gold Plated Princess', 9.99, N'Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine''s Day...', N'jewelery', N'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg', 3, 400)
INSERT INTO [dbo].[Product] ([Id], [Title], [Price], [Description], [Category], [Image], [RatingRate], [RatingCount]) VALUES (8, N'Pierced Owl Rose Gold Plated Stainless Steel Double', 10.99, N'Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel', N'jewelery', N'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg', 1.9, 100)
INSERT INTO [dbo].[Product] ([Id], [Title], [Price], [Description], [Category], [Image], [RatingRate], [RatingCount]) VALUES (9, N'WD 2TB Elements Portable External Hard Drive - USB 3.0', 64, N'USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system', N'electronics', N'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg', 3.3, 203)
INSERT INTO [dbo].[Product] ([Id], [Title], [Price], [Description], [Category], [Image], [RatingRate], [RatingCount]) VALUES (10, N'SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s', 109, N'Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)', N'electronics', N'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg', 2.9, 470)
INSERT INTO [dbo].[Product] ([Id], [Title], [Price], [Description], [Category], [Image], [RatingRate], [RatingCount]) VALUES (11, N'Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5', 109, N'3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RA and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.', N'electronics', N'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg', 4.8, 319)
INSERT INTO [dbo].[Product] ([Id], [Title], [Price], [Description], [Category], [Image], [RatingRate], [RatingCount]) VALUES (12, N'WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive', 114, N'Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer''s limited warranty', N'electronics', N'https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg', 4.8, 400)
INSERT INTO [dbo].[Product] ([Id], [Title], [Price], [Description], [Category], [Image], [RatingRate], [RatingCount]) VALUES (13, N'Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin', 599, N'21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz', N'electronics', N'https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg', 2.9, 250)
INSERT INTO [dbo].[Product] ([Id], [Title], [Price], [Description], [Category], [Image], [RatingRate], [RatingCount]) VALUES (14, N'Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED', 999.99, N'49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag', N'electronics', N'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg', 2.2, 140)
INSERT INTO [dbo].[Product] ([Id], [Title], [Price], [Description], [Category], [Image], [RatingRate], [RatingCount]) VALUES (15, N'BIYLACLESEN Women''s 3-in-1 Snowboard Jacket Winter Coats', 56.99, N'Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates', N'women''s clothing', N'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg', 2.6, 235)
INSERT INTO [dbo].[Product] ([Id], [Title], [Price], [Description], [Category], [Image], [RatingRate], [RatingCount]) VALUES (16, N'Lock and Love Women''s Removable Hooded Faux Leather Moto Biker Jacket', 29.95, N'100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON', N'women''s clothing', N'https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg', 2.9, 340)
INSERT INTO [dbo].[Product] ([Id], [Title], [Price], [Description], [Category], [Image], [RatingRate], [RatingCount]) VALUES (17, N'Rain Jacket Women Windbreaker Striped Climbing Raincoats', 39.99, N'Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn''t overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.', N'women''s clothing', N'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg', 3.8, 679)
INSERT INTO [dbo].[Product] ([Id], [Title], [Price], [Description], [Category], [Image], [RatingRate], [RatingCount]) VALUES (18, N'MBJ Women''s Solid Short Sleeve Boat Neck V', 9.85, N'95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem', N'women''s clothing', N'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg', 4.7, 130)
INSERT INTO [dbo].[Product] ([Id], [Title], [Price], [Description], [Category], [Image], [RatingRate], [RatingCount]) VALUES (19, N'Opna Women''s Short Sleeve Moisture', 7.95, N'100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort', N'women''s clothing', N'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg', 4.5, 146)
INSERT INTO [dbo].[Product] ([Id], [Title], [Price], [Description], [Category], [Image], [RatingRate], [RatingCount]) VALUES (20, N'DANVOUY Womens T Shirt Casual Cotton Short', 12.99, N'95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.', N'women''s clothing', N'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg', 3.6, 145)
Go


--Bank Table
CREATE TABLE [dbo].[Bank] (
    [Id]       INT            IDENTITY (1, 1) NOT NULL,
    [BankName] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_Bank] PRIMARY KEY CLUSTERED ([Id] ASC)
);
Go

Go
--Insert into Bank 

INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (1, N'ABHYUDAYA COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (2, N'ABU DHABI COMMERCIAL BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (3, N'AHMEDABAD MERCANTILE COOPERATIVE BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (4, N'AHMEDNAGAR MERCHANTS CO-OP BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (5, N'AIRTEL PAYMENTS BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (6, N'AKOLA JANATA COMMERCIAL COOPERATIVE BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (7, N'ALLAHABAD BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (8, N'ALMORA URBAN COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (9, N'AMBARNATH JAIHIND COOP BANK LTD AMBARNATH')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (10, N'ANDHRA BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (11, N'ANDHRA PRADESH GRAMEENA VIKAS BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (12, N'ANDHRA PRAGATHI GRAMEENA BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (13, N'APNA SAHAKARI BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (14, N'AU SMALL FINANCE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (15, N'AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (16, N'AXIS BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (17, N'B N P PARIBAS')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (18, N'BANDHAN BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (19, N'BANK OF AMERICA')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (20, N'BANK OF BAHARAIN AND KUWAIT BSC')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (21, N'BANK OF BARODA')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (22, N'BANK OF CEYLON')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (23, N'BANK OF INDIA')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (24, N'BANK OF MAHARASHTRA')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (25, N'BARCLAYS BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (26, N'BASSEIN CATHOLIC COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (27, N'BHAGINI NIVEDITA SAHAKARI BANK LTD PUNE')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (28, N'BHARAT COOPERATIVE BANK MUMBAI LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (29, N'CANARA BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (30, N'CAPITAL SMALL FINANCE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (31, N'CENTRAL BANK OF INDIA')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (32, N'CITI BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (33, N'CITIZEN CREDIT COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (34, N'CITY UNION BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (35, N'CORPORATION BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (36, N'CREDIT AGRICOLE CORPORATE AND INVESTMENT BANK CALYON BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (37, N'CREDIT SUISEE AG')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (38, N'CSB BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (39, N'CTBC BANK CO LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (40, N'DBS BANK INDIA LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (41, N'DCB BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (42, N'DENA BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (43, N'DEOGIRI NAGARI SAHAKARI BANK LTD. AURANGABAD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (44, N'DEPOSIT INSURANCE AND CREDIT GUARANTEE CORPORATION')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (45, N'DEUSTCHE BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (46, N'DHANALAKSHMI BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (47, N'DMK JAOLI BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (48, N'DOHA BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (49, N'DOMBIVLI NAGARI SAHAKARI BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (50, N'DURGAPUR STEEL PEOPLES CO-OPERATIVE BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (51, N'EMIRATES NBD BANK P J S C')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (52, N'EQUITAS SMALL FINANCE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (53, N'ESAF SMALL FINANCE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (54, N'EXPORT IMPORT BANK OF INDIA')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (55, N'FEDERAL BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (56, N'FINCARE SMALL FINANCE BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (57, N'FINO PAYMENTS BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (58, N'FIRST ABU DHABI BANK PJSC')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (59, N'FIRSTRAND BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (60, N'G P PARSIK BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (61, N'GS Mahanagar Co-operative Bank Limited, Mumbai')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (62, N'HARYANA STATE COOPERATIVE BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (63, N'HDFC BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (64, N'HIMACHAL PRADESH STATE COOPERATIVE BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (65, N'HSBC BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (66, N'ICICI BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (67, N'IDBI BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (68, N'IDFC First Bank Ltd')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (69, N'IDUKKI DISTRICT CO OPERATIVE BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (70, N'INDIA POST PAYMENT BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (71, N'INDIAN BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (72, N'INDIAN OVERSEAS BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (73, N'INDUSIND BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (74, N'INDUSTRIAL AND COMMERCIAL BANK OF CHINA LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (75, N'INDUSTRIAL BANK OF KOREA')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (76, N'Irinjalakuda Town Co-Operative Bank Ltd')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (77, N'JALGAON JANATA SAHAKARI BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (78, N'JAMMU AND KASHMIR BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (79, N'JANA SMALL FINANCE BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (80, N'JANAKALYAN SAHAKARI BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (81, N'JANASEVA SAHAKARI BANK BORIVLI LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (82, N'JANASEVA SAHAKARI BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (83, N'JANATA SAHAKARI BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (84, N'JIO PAYMENTS BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (85, N'JP MORGAN BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (86, N'KALLAPPANNA AWADE ICHALKARANJI JANATA SAHAKARI BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (87, N'KALUPUR COMMERCIAL COOPERATIVE BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (88, N'KALYAN JANATA SAHAKARI BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (89, N'KARNATAKA BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (90, N'KARNATAKA VIKAS GRAMEENA BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (91, N'KARUR VYSYA BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (92, N'KAVERI GRAMEENA BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (93, N'KEB Hana Bank')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (94, N'KERALA GRAMIN BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (95, N'KOTAK MAHINDRA BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (96, N'KOZHIKODE DISTRICT COOPERATIAVE BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (97, N'KRUNG THAI BANK PCL')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (98, N'LAXMI VILAS BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (99, N'Maharashtra Gramin Bank')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (100, N'MAHARASHTRA STATE COOPERATIVE BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (101, N'Mahesh Sahakari Bank Ltd Pune')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (102, N'MASHREQBANK PSC')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (103, N'MIZUHO BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (104, N'MUFG BANK, LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (105, N'NAGAR URBAN CO OPERATIVE BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (106, N'NAGPUR NAGARIK SAHAKARI BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (107, N'NATIONAL BANK FOR AGRICULTURE AND RURAL DEVELOPMENT')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (108, N'NAV JEEVAN CO OP BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (109, N'NEW INDIA COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (110, N'NKGSB COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (111, N'NORTH EAST SMALL FINANCE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (112, N'NSDL Payments Bank Limited')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (113, N'NUTAN NAGARIK SAHAKARI BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (114, N'ORIENTAL BANK OF COMMERCE')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (115, N'PAYTM PAYMENTS BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (116, N'PRAGATHI KRISHNA GRAMIN BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (117, N'PRIME COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (118, N'PT BANK MAYBANK INDONESIA TBK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (119, N'PUNJAB AND SIND BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (120, N'PUNJAB NATIONAL BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (121, N'QATAR NATIONAL BANK SAQ')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (122, N'RABOBANK INTERNATIONAL')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (123, N'RAJARAMBAPU SAHAKARI BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (124, N'RAJASTHAN MARUDHARA GRAMIN BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (125, N'RAJGURUNAGAR SAHAKARI BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (126, N'RAJKOT NAGRIK SAHAKARI BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (127, N'RBL Bank Limited')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (128, N'RESERVE BANK OF INDIA')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (129, N'SAHEBRAO DESHMUKH COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (130, N'SAMARTH SAHAKARI BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (131, N'SANT SOPANKAKA SAHAKARI BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (132, N'Saraspur Nagrik Co operative Bank Ltd Saraspur')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (133, N'SARASWAT COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (134, N'SBER BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (135, N'SBM BANK INDIA LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (136, N'SHIKSHAK SAHAKARI BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (137, N'SHINHAN BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (138, N'SHIVALIK MERCANTILE CO OPERATIVE BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (139, N'SHRI CHHATRAPATI RAJASHRI SHAHU URBAN COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (140, N'Shri Veershaiv Co Op Bank Ltd')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (141, N'SIR M VISVESVARAYA CO OPERATIVE BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (142, N'SOCIETE GENERALE')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (143, N'SOLAPUR JANATA SAHAKARI BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (144, N'SOUTH INDIAN BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (145, N'STANDARD CHARTERED BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (146, N'STATE BANK OF INDIA')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (147, N'SUMITOMO MITSUI BANKING CORPORATION')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (148, N'SURAT NATIONAL COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (149, N'SURYODAY SMALL FINANCE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (150, N'SUTEX COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (151, N'SYNDICATE BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (152, N'TAMILNAD MERCANTILE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (153, N'TELANGANA STATE COOP APEX BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (154, N'TEXTILE TRADERS CO OPERATIVE BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (155, N'THE A.P. MAHESH COOPERATIVE URBAN BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (156, N'The Ajara Urban Co op Bank Ltd Ajara')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (157, N'THE AKOLA DISTRICT CENTRAL COOPERATIVE BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (158, N'THE ANDHRA PRADESH STATE COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (159, N'THE BANK OF NOVA SCOTIA')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (160, N'THE BARAMATI SAHAKARI BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (161, N'THE COSMOS CO OPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (162, N'THE DELHI STATE COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (163, N'THE GADCHIROLI DISTRICT CENTRAL COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (164, N'THE GREATER BOMBAY COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (165, N'THE GUJARAT STATE COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (166, N'THE HASTI COOP BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (167, N'THE JALGAON PEOPELS COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (168, N'THE KANGRA CENTRAL COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (169, N'THE KANGRA COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (170, N'THE KARAD URBAN COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (171, N'THE KARANATAKA STATE COOPERATIVE APEX BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (172, N'The Kerala State Co Operative Bank Ltd')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (173, N'THE KURMANCHAL NAGAR SAHAKARI BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (174, N'The Malkapur Urban Co Operative Bank Ltd Malkapur')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (175, N'THE MEHSANA URBAN COOPERATIVE BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (176, N'THE MUMBAI DISTRICT CENTRAL COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (177, N'THE MUNICIPAL COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (178, N'The Muslim Co-operative Bank Ltd')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (179, N'THE NAINITAL BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (180, N'THE NASIK MERCHANTS COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (181, N'THE NAVNIRMAN CO-OPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (182, N'THE NILAMBUR CO OPERATIVE URBAN BANK LTD NILAMBUR')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (183, N'THE ODISHA STATE COOPERATIVE BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (184, N'THE PANDHARPUR URBAN CO OP. BANK LTD. PANDHARPUR')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (185, N'THE RAJASTHAN STATE COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (186, N'THE SEVA VIKAS COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (187, N'THE SHAMRAO VITHAL COOPERATIVE BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (188, N'THE SINDHUDURG DISTRICT CENTERIAL CO-OP BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (189, N'THE SURAT DISTRICT COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (190, N'THE SURATH PEOPLES COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (191, N'THE TAMIL NADU STATE APEX COOPERATIVE BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (192, N'THE THANE BHARAT SAHAKARI BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (193, N'THE THANE DISTRICT CENTRAL COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (194, N'THE URBAN CO OPERATIVE BANK Ltd No ONE SEVEN FIVE EIGHT PERINTHALMANNA')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (195, N'THE VARACHHA COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (196, N'The Vijay Co Operative Bank Limited')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (197, N'THE VISHWESHWAR SAHAKARI BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (198, N'THE WEST BENGAL STATE COOPERATIVE BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (199, N'THE ZOROASTRIAN COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (200, N'THRISSUR DISTRICT CO-OPERATIVE BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (201, N'TJSB SAHAKARI BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (202, N'TUMKUR GRAIN MERCHANTS COOPERATIVE BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (203, N'UCO BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (204, N'Ujjivan Small Finance Bank Limited')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (205, N'UNION BANK OF INDIA')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (206, N'UNITED BANK OF INDIA')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (207, N'UNITED OVERSEAS BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (208, N'UTKARSH SMALL FINANCE BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (209, N'UTTAR PRADESH COOPERATIVE BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (210, N'VASAI JANATA SAHAKARI BANK LTD')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (211, N'VASAI VIKAS SAHAKARI BANK LIMITED')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (212, N'VIJAYA BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (213, N'WESTPAC BANKING CORPORATION')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (214, N'WOORI BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (215, N'YES BANK')
INSERT INTO [dbo].[Bank] ([Id], [BankName]) VALUES (216, N'ZILA SAHAKRI BANK LIMITED GHAZIABAD')
Go